//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTeam
    {
        public int EventId { get; set; }
        public int TeamId { get; set; }
        public int OutcomeId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Lookup_Outcome Lookup_Outcome { get; set; }
        public virtual Team Team { get; set; }
    }
}
