//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture
    {
        public int FixtureId { get; set; }
        public int EventId { get; set; }
        public int HomeTeam { get; set; }
        public int AwayTeam { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
